apiVersion: apps/v1
kind: Deployment
metadata:
  name: kobot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kobot
  template:
    metadata:
      labels:
        app: kobot
    spec:
      containers:
      - image: okteto.dev/kobot:latest
        name: kobot
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "6ab0d44a-7260-4569-b984-25703d4fa885"
        - name: Vless_Path
          value: "/kdiwdll"
        - name: Vmess_UUID
          value: "160293f6-33bd-4f75-8d10-22e8c2603245"
        - name: Vmess_Path
          value: "/wmdisou"
        - name: Share_Path
          value: "/v2link"
